### PR TITLE
Snap 2900

### PR DESCRIPTION
**Pull request by snappy-sachin**
## What changes were proposed in this pull request?

Proposals:
 * SNAP-2900 : Provide an ability/control, on Dashboard UI, to expand or collapse whole row per member node entry in single click
 * SNAP-2908 : Display Sparklines  (inline charts) for CPU and Memory usages for individual members in Members List

Changes:
 - Adding HTML, CSS, and JavaScript code changes for adding Expand and Collapse control button against each members list entry. Clicking on this control button all addition cell details will be displayed or hidden.
 - Similarly adding parent expand and collapse control to expand and collapse all rows in the table in single click.
 - Removing existing  Expand and Collapse control buttons per cell, as those will be redundant.
 - Adding third party library Jquery Sparklines to add sparklines (inline charts) in members list for CPU and Memory Usages.
 - Adding HTML, CSS, and JavaScript code changes for rendering CPU and Memory usages Sparklines.
 - Code clean up.

Note:
  UI screenshots are attached in Jira tickets:
    https://jira.snappydata.io/browse/SNAP-2900
    https://jira.snappydata.io/browse/SNAP-2908

## How was this patch tested?

 - Tested Manually

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Review by ashetkar — APPROVED** [review]
Looked at the screenshots in SNAP-2900 and looks good to me.

As a side note, a miniature button (+/-) to expand all or collapse all would be great too, in addition to this feature. Specially for monitoring relatively bigger clusters.

**Comment by ashetkar** [comment]
One more suggestion: I think it would be better to keep the expand/collapse arrow mark on the right side instead of the left side of each entry.

Earlier, three arrow marks per entry were on the right side of the respective columns.

**Comment by snappy-sachin** [comment]
> Looked at the screenshots in SNAP-2900 and looks good to me.
> 
> As a side note, a miniature button (+/-) to expand all or collapse all would be great too, in addition to this feature. Specially for monitoring relatively bigger clusters.

As suggested, I have added a parent expand/collapse icon control to expand and collapse all rows in the table in single click.

**Comment by snappy-sachin** [comment]
> One more suggestion: I think it would be better to keep the expand/collapse arrow mark on the right side instead of the left side of each entry.
> 
> Earlier, three arrow marks per entry were on the right side of the respective columns.

It's a standard practice to keep user controls on left most side when it affects the whole row in the table where as if the table cell specific control is to be placed then such control is placed on right side within that table cell besides its content.
Also keeping such row level user control on right side may get hidden if number of columns goes beyond visible area and table displays horizontal scroll (as of now Snappy UI doesn't have it). Therefore user may not notice that there is expand and collapse row feature in the table.

**Comment by snappy-sachin** [comment]
All feedback have been taken care. Hence Merging.

**Pull request merged**
