### PR TITLE
Changes for SNAP-2974 : Snappy UI re-branding to TIBCO ComputeDB

### PR DESCRIPTION
**Pull request by snappy-sachin**
## What changes were proposed in this pull request?

  1. Adding TIBCO ComputDB product logo
  2. Adding Help Icon, clicking on which About box is displayed
  3. Updating About Box content
     - Adding TIBCO ComputeDB product name and its Edition type
     - Adding Copyright information
     - Adding Assistance details web links
     - Adding Documentation link
  4. Removing or Changing user visible SnappyData references on UI to TIBCO ComputeDB.
  5. Renaming pages to just Dashboard, Member Details and Jobs
  6. Removing Docs link from tabs bar

## How was this patch tested?

 - Tested manually

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by dshirish** [comment]
Check why some of the changes in PR are being marked red in PR

**Review by dshirish — APPROVED** [review]
LGTM

**Comment by snappy-sachin** [comment]
> Check why some of the changes in PR are being marked red in PR

Renamed "Documentations" to "Product Documentation", as discussed with Lizy.

Although there is no syntax error, why is PR changes shown in red background needs investigation.

**Comment by snappy-sachin** [comment]
Merging.

**Pull request merged**
